import type { Config } from 'tailwindcss'

const config: Config = {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: '#854d67',
        'primary-container': '#ffb7d5',
        'primary-fixed': '#ffd8e6',
        'primary-fixed-dim': '#fab2d0',
        'on-primary': '#ffffff',
        'on-primary-container': '#7c445e',
        'on-primary-fixed': '#360a22',
        'on-primary-fixed-variant': '#6a364f',
        secondary: '#6b5195',
        'secondary-container': '#d1b3ff',
        'secondary-fixed': '#ecdcff',
        'secondary-fixed-dim': '#d6baff',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#5b4184',
        'on-secondary-fixed': '#26084d',
        'on-secondary-fixed-variant': '#53397c',
        tertiary: '#266a4b',
        'tertiary-container': '#95dab4',
        'tertiary-fixed': '#acf2ca',
        'tertiary-fixed-dim': '#91d5af',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#1b6143',
        'on-tertiary-fixed': '#002113',
        'on-tertiary-fixed-variant': '#015235',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        background: '#f9f9f9',
        surface: '#f9f9f9',
        'surface-bright': '#f9f9f9',
        'surface-dim': '#dadada',
        'surface-variant': '#e2e2e2',
        'surface-container': '#eeeeee',
        'surface-container-low': '#f3f3f4',
        'surface-container-lowest': '#ffffff',
        'surface-container-high': '#e8e8e8',
        'surface-container-highest': '#e2e2e2',
        'on-background': '#1a1c1c',
        'on-surface': '#1a1c1c',
        'on-surface-variant': '#504348',
        outline: '#837378',
        'outline-variant': '#d4c2c7',
        'inverse-surface': '#2f3131',
        'inverse-on-surface': '#f0f1f1',
        'inverse-primary': '#fab2d0',
        'surface-tint': '#854d67',
      },
      borderRadius: {
        sm: '0.5rem',
        DEFAULT: '1rem',
        md: '1.5rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
      spacing: {
        xs: '4px',
        sm: '12px',
        md: '24px',
        lg: '48px',
        xl: '80px',
        gutter: '24px',
        'margin-mobile': '16px',
        'margin-desktop': '64px',
      },
      fontFamily: {
        display: ['"Plus Jakarta Sans"', 'sans-serif'],
        body: ['Quicksand', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '56px', fontWeight: '800', letterSpacing: '-0.02em' }],
        'display-mobile': ['32px', { lineHeight: '40px', fontWeight: '800' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '500' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '500' }],
        'label-caps': ['14px', { lineHeight: '20px', fontWeight: '700' }],
      },
      keyframes: {
        float: {
          '0%, 100%': { transform: 'translateY(0px) rotate(0deg)' },
          '50%': { transform: 'translateY(-15px) rotate(5deg)' },
        },
        'float-reverse': {
          '0%, 100%': { transform: 'translateY(0px) rotate(0deg)' },
          '50%': { transform: 'translateY(15px) rotate(-5deg)' },
        },
        'pulse-glow': {
          '0%, 100%': { boxShadow: '0 0 10px rgba(255,183,213,0.5)' },
          '50%': { boxShadow: '0 0 30px rgba(209,179,255,0.8)' },
        },
        shimmer: {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
        wiggle: {
          '0%, 100%': { transform: 'rotate(-3deg)' },
          '50%': { transform: 'rotate(3deg)' },
        },
        'bounce-soft': {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-8px)' },
        },
      },
      animation: {
        float: 'float 4s ease-in-out infinite',
        'float-delayed': 'float 5s ease-in-out 2s infinite',
        'float-reverse': 'float-reverse 4.5s ease-in-out 1s infinite',
        'pulse-glow': 'pulse-glow 3s ease-in-out infinite',
        shimmer: 'shimmer 2s linear infinite',
        wiggle: 'wiggle 1s ease-in-out infinite',
        'bounce-soft': 'bounce-soft 2s ease-in-out infinite',
      },
    },
  },
  plugins: [],
}

export default config
